# Data analysis notebook

In [6]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(Path().resolve().parent))

from config import RAW_DATA_DIR, PROCESSED_DATA_DIR, STATIONS

In [7]:
import json
import requests

from datetime import datetime, timedelta, timezone
from pprint import pprint

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
milan_lampugnano_df = pd.read_csv(PROCESSED_DATA_DIR / 'milan_lampugnano_departures.csv')
genoa_principe_df = pd.read_csv(PROCESSED_DATA_DIR / 'genoa_principe_departures.csv')

In [9]:
milan_lampugnano_df.head()

,id,bus_code,direction,name,deviation_seconds,updated_at,scheduled_timestamp
0,23c8dea6-ab2f-429c-ba95-545b24835042,N456,"Lublin, Bus Station Lublin",Lublin - Milan - Marseille,2859.0,2026-05-20T16:12:41Z,2026-05-20T16:35:00Z
1,279429f3-5d1a-4c7b-a7f8-b2d520720fc8,518,Como,Naples - Milan - Como,0.0,2026-05-20T04:48:55Z,2026-05-20T17:25:00Z
2,f54c0343-266b-4ebc-804e-0228733d2e5a,423,Turin (Vittorio Emanuele),Turin - Ferrara,263.0,2026-05-20T16:18:27Z,2026-05-20T17:30:00Z
3,afeed613-2e47-4b8a-865d-ea644648ff3d,N836,Amsterdam Sloterdijk,Amsterdam - Brussels - Luxemburg - Milan,NaN,NaN,2026-05-20T17:40:00Z
4,7f008d8a-46b9-4a06-9fa6-4a01f7294883,CIT3197,Milan (Malpensa Airport Terminal 1),Standard,NaN,NaN,2026-05-20T17:45:00Z

In [10]:
genoa_principe_df.head()

,id,bus_code,direction,name,deviation_seconds,updated_at,scheduled_timestamp
0,4a8a8865-2806-4f83-869e-bda601b25a60,501,Turin (Vittorio Emanuele),Turin - Naples,0.0,2026-05-20T16:12:24Z,2026-05-20T17:55:00Z
1,c36a991e-02a2-4da2-b7b0-6a0bf3f1979f,N758,Barcelona (Bus Terminal Nord),Florence - Barcelona,0.0,2026-05-20T16:16:23Z,2026-05-20T19:25:00Z
2,fb971887-fb5f-4f70-9ee3-51f98e2df1f0,N177,Düsseldorf central bus station,Düsseldorf - Genoa,NaN,NaN,2026-05-20T19:30:00Z
3,0aa24a02-20c3-4546-a0da-7204720f792e,N728,Munich central bus station,Munich/Genoa - Barcelona,0.0,2026-05-20T06:52:32Z,2026-05-20T21:05:00Z
4,3e59c7ef-b056-405d-a477-9fe1df21eeb9,N504,Perugia (Piazza Partigiani),Geneva - Turin - Perugia,0.0,2026-05-20T16:09:23Z,2026-05-20T21:20:00Z